# config.yaml
apprise:
  summary: on_error
  urls:
    - 'discord://1249322805644755006/xZ14P7DGCeamge6q1avUqMIe_iO804twJQaibxHXQeMZtwJkiTZ8vZDBQdFyYNquj0FX'  # Replace with your actual Apprise service URLs
